### ISSUE TITLE
Blank invoice generated

### ISSUE THREAD

**Issue by davidawad** [saadq/cc-invoice#2]
generates blank invoice : ( 

maybe drop some JS alerts upon failures?

**Comment by ronakdpatel** [comment]
Do you have excel installed? If you are using LibreOffice, it doesn't open the xls file properly for some reason. There's a "bootleg" work around if you don't have excel installed though.

**Comment by saadq** [comment]
Could you attach the generated XLS file here? Also, what OS are you on? And yeah, just to reiterate what Ronak said, what program did you try opening this file with?

**Comment by saadq** [comment]
I believe this issue has been resolved outside of the discussion here, the gist of it was that the file starts off blank until it has finished loading, so waiting for the excel sheet to load is all that needs to be done.

Closing for now.
